services:
  rabbitmq:
    image: registry.docker.ir/rabbitmq:3.12-management-alpine
    container_name: rabbitmq-run1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

    restart: always