workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^stage/
      changes:
        - deploy/basket/**
        - cmd/basket/**
        - repository/mysql/basket/**
        - service/basket/**
        - adapter/**
        - pkg/**