basket_server:
  port: 5000
postgres_basket_db:
  host: localhost
  port: 5433
  user: "basket_admin"
  password: "password123"
  db_name: basket_db
  ssl_mode: disable
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_lifetime: 5  
