development:
  dialect: postgres
  datasource: host=localhost port=5433 dbname=basket_db user=basket_admin password=Pass@Admin#8273 sslmode=disable
  dir: migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=prodhost dbname=proddb user=${DB_USER} password=${DB_PASSWORD} sslmode=require
  dir: migrations
  table: migrations